# Generated by Django 3.2.5 on 2021-07-07 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdtrackTest',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('timestamp', models.CharField(max_length=23)),
                ('platformtype', models.CharField(max_length=7)),
                ('devicemodel', models.CharField(max_length=25)),
                ('imagename', models.CharField(max_length=35)),
                ('imageurl', models.CharField(max_length=73)),
                ('userid', models.IntegerField()),
                ('companyid', models.CharField(blank=True, max_length=2, null=True)),
                ('brandname', models.CharField(max_length=78)),
                ('name', models.CharField(max_length=24)),
                ('is_youtube', models.CharField(max_length=1)),
                ('gdrivelink', models.CharField(max_length=33)),
                ('destinationlink', models.CharField(blank=True, max_length=255, null=True)),
                ('firstname', models.CharField(max_length=12)),
                ('lastname', models.CharField(max_length=10)),
                ('category_name', models.CharField(max_length=23)),
                ('advertisername', models.CharField(blank=True, max_length=69, null=True)),
            ],
            options={
                'db_table': 'adtrack_test',
            },
        ),
    ]
