# Generated by Django 3.2.5 on 2021-07-07 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adtracktest',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
